// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmw_Lrkg_ktR5WXtMKoEj4iuBeoVDmCVw',
    appId: '1:947127439724:web:60dbf8a5f09d8d5251e349',
    messagingSenderId: '947127439724',
    projectId: 'checklistapp-c038d',
    authDomain: 'checklistapp-c038d.firebaseapp.com',
    storageBucket: 'checklistapp-c038d.appspot.com',
    measurementId: 'G-9JCKJY2ZCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhTx-mUYLFh5EfVxPdFHF0FyHduzDSePY',
    appId: '1:947127439724:android:19484678b385d0cc51e349',
    messagingSenderId: '947127439724',
    projectId: 'checklistapp-c038d',
    storageBucket: 'checklistapp-c038d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6iu5xM78gEVnvz2y8daQNNwVUwRS8T-M',
    appId: '1:947127439724:ios:ab2e5612e24a975151e349',
    messagingSenderId: '947127439724',
    projectId: 'checklistapp-c038d',
    storageBucket: 'checklistapp-c038d.appspot.com',
    iosBundleId: 'com.example.prototipo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6iu5xM78gEVnvz2y8daQNNwVUwRS8T-M',
    appId: '1:947127439724:ios:ab2e5612e24a975151e349',
    messagingSenderId: '947127439724',
    projectId: 'checklistapp-c038d',
    storageBucket: 'checklistapp-c038d.appspot.com',
    iosBundleId: 'com.example.prototipo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmw_Lrkg_ktR5WXtMKoEj4iuBeoVDmCVw',
    appId: '1:947127439724:web:79f2f7677df4ee2051e349',
    messagingSenderId: '947127439724',
    projectId: 'checklistapp-c038d',
    authDomain: 'checklistapp-c038d.firebaseapp.com',
    storageBucket: 'checklistapp-c038d.appspot.com',
    measurementId: 'G-7PT71LEREB',
  );
}
